[versions]
com-fasterxml-jackson-module-jackson-module-kotlin = "2.17.2"
com-google-guava-guava = "33.1.0-jre"
com-h2database-h2 = "2.2.224"
io-ktor-ktor-client-cio-jvm = "3.1.3"
io-ktor-ktor-client-content-negotiation-jvm = "3.1.3"
io-ktor-ktor-client-core-jvm = "3.1.3"
io-ktor-ktor-serialization-kotlinx-json-jvm = "3.1.3"
io-milton-milton-server-ce = "4.0.4.2305"
io-mockk-mockk = "1.13.13"
io-mockk-mockk-jvm = "1.13.13"
org-jetbrains-kotlin-kotlin-reflect = "2.0.21"
org-jetbrains-kotlin-kotlin-stdlib = "2.0.21"
org-jetbrains-kotlin-kotlin-test = "2.0.21"
org-jetbrains-kotlinx-kotlinx-coroutines-core = "1.10.0"
org-jetbrains-kotlinx-kotlinx-coroutines-test = "1.9.0"
org-jetbrains-kotlinx-kotlinx-serialization-json-jvm = "1.7.3"
org-mock-server-mockserver-netty-no-dependencies = "5.14.0"
org-mockito-kotlin-mockito-kotlin = "5.2.1"
org-postgresql-postgresql = "42.7.2"
org-springframework-boot-spring-boot-starter-data-jpa = "3.4.6"
org-springframework-boot-spring-boot-starter-test = "3.4.6"
org-springframework-boot-spring-boot-starter-web = "3.4.6"
org-springframework-boot-spring-boot-starter-webflux = "3.4.6"

[libraries]
com-fasterxml-jackson-module-jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "com-fasterxml-jackson-module-jackson-module-kotlin" }
com-google-guava-guava = { module = "com.google.guava:guava", version.ref = "com-google-guava-guava" }
io-ktor-ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "io-ktor-ktor-client-cio-jvm" }
io-ktor-ktor-client-content-negotiation-jvm = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "io-ktor-ktor-client-content-negotiation-jvm" }
io-ktor-ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "io-ktor-ktor-client-core-jvm" }
io-ktor-ktor-serialization-kotlinx-json-jvm = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "io-ktor-ktor-serialization-kotlinx-json-jvm" }
io-milton-milton-server-ce = { module = "io.milton:milton-server-ce", version.ref = "io-milton-milton-server-ce" }
io-mockk-mockk = { module = "io.mockk:mockk", version.ref = "io-mockk-mockk" }
io-mockk-mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "io-mockk-mockk-jvm" }
org-jetbrains-kotlin-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "org-jetbrains-kotlin-kotlin-reflect" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin-kotlin-stdlib" }
org-jetbrains-kotlin-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "org-jetbrains-kotlin-kotlin-test" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-core" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-test" }
org-jetbrains-kotlinx-kotlinx-serialization-json-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "org-jetbrains-kotlinx-kotlinx-serialization-json-jvm" }
org-mock-server-mockserver-netty-no-dependencies = { module = "org.mock-server:mockserver-netty-no-dependencies", version.ref = "org-mock-server-mockserver-netty-no-dependencies" }
org-mockito-kotlin-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "org-mockito-kotlin-mockito-kotlin" }
org-postgresql-postgresql = { module = "org.postgresql:postgresql", version.ref = "org-postgresql-postgresql" }
org-springframework-boot-spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "org-springframework-boot-spring-boot-starter-data-jpa" }
org-springframework-boot-spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "org-springframework-boot-spring-boot-starter-test" }
org-springframework-boot-spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "org-springframework-boot-spring-boot-starter-web" }
org-springframework-boot-spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "org-springframework-boot-spring-boot-starter-webflux" }
