services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - debridav-monitoring-network
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/defaults.ini:/etc/grafana/defaults.ini
    networks:
      - debridav-monitoring-network
  postgres-metrics-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_URI=${DEBRIDAV_DB_HOST}:${DEBRIDAV_DB_PORT}/${DEBRIDAV_DB_DATABASE_NAME}?sslmode=disable
      - DATA_SOURCE_USER=${DEBRIDAV_DB_USERNAME}
      - DATA_SOURCE_PASS=${DEBRIDAV_DB_PASSWORD}
      - PG_EXPORTER_EXTEND_QUERY_PATH=/custom-queries/queries.yaml
    volumes:
      - ./pg-exporter/custom-queries:/custom-queries
    ports:
      - "9187:9187"
    networks:
      - debridav-monitoring-network
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:8080"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    ports:
      - "8083:8080"
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - debridav-monitoring-network
networks:
  debridav-monitoring-network:
    external:
      name: debridav

