---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin-debridav
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_FFmpeg__probesize=30M
      - JELLYFIN_FFmpeg__analyzeduration=10M
    #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    ports:
      - "8096:8096"
      - "8920:8920" #optional
      - "7359:7359/udp" #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped
    depends_on:
      - rclone
    volumes:
      - ./jellyfin-config:/config
      - ${DEBRIDAV_MOUNT_PATH_HOST_FS}:${DEBRIDAV_MOUNT_PATH_CONTAINERS}:rshared
